# Python Packages Numpy and Pandas

#### Refferences
https://www.pluralsight.com/guides/overview-basic-numpy-operations

In [1]:
#Importing packages with alias
import pandas as pd
import numpy as np

### Numpy

In [2]:
#creating a series of numbers lets say 1 to 15

a =np.arange(15) ## 0 to n-1, here (15-1)
b =np.arange(5,15) ## starting from 5 to 14
c =np.arange(0,15,2) ## staring form 1 to 14, with an interval of 2

print(" a=",a,"\n","b=",b,"\n","c=",c)

 a= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
 b= [ 5  6  7  8  9 10 11 12 13 14] 
 c= [ 0  2  4  6  8 10 12 14]


In [3]:
# 'a' is 1x15 in dimension, to convert it to 3x5
print ("reshape function \n",a.reshape(3,5),"\n") ## the change is temporary
print("checking after reshape function \n",a,"\n")
a.resize(3,5)  ## the change is permenant
print("check for a after resize \n",a)

reshape function 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

checking after reshape function 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

check for a after resize 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
#Creating a multi diamentional array
np.random.randint(1,25,size=(5,4))

array([[ 1,  3, 19, 22],
       [21, 23, 15,  3],
       [13, 12,  5, 13],
       [19, 24,  8, 22],
       [22, 17,  2,  8]])

##### There are a lot of functions, all of which cannot be explanined. if done so this will become the help file. <br>  So pls be familiar with the commands and the remaining things like syntax and useage could be obtained form inbuilt help/google

Help about a pirticular function can be obtained as follows. <br>
To see list of functions avaiable on numpy. <br>
just type "numpy." or "np."(if using alias)  and press tab

In [5]:
# Syntax
# np.info(np.function_name)
np.info(np.random.randint)

randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

Parameters
----------
low : int
    Lowest (signed) integer to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result. All dtypes are determined by their
    name, i.e., 'int64', 'int'

In [6]:
print(a,"\n")
print("the shape of array a:",a.shape)
print("the dimension of array a:",a.ndim)
print("the total no of elements in array a:",a.size)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

the shape of array a: (3, 5)
the dimension of array a: 2
the total no of elements in array a: 15


In [7]:
#array creation
aa =np.array([1,2,3,4,5])  ## Regular array
ab=np.array([[1, 2], [3, 4]]) ## Multi dimesnional array
ac=np.array([[1,2],[5,6]],dtype = complex) ## complex

print ("Regular Array\n",aa, "\nMulti Dimensional Array\n",ab,"\nComplex Array\n",ac)

Regular Array
 [1 2 3 4 5] 
Multi Dimensional Array
 [[1 2]
 [3 4]] 
Complex Array
 [[1.+0.j 2.+0.j]
 [5.+0.j 6.+0.j]]


In [8]:
## Few more numpy operations

print(np.zeros((2,2)))
print("\n")
print(np.ones((2,2),dtype = int))

[[0. 0.]
 [0. 0.]]


[[1 1]
 [1 1]]


In [9]:
#operations in numpy lists

A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print("A= \n",A,"\nB=\n",B)

A= 
 [[1 1]
 [0 1]] 
B=
 [[2 0]
 [3 4]]


In [10]:
print(A*B,"\n")         ## Element wise multiplication
print("\n",A.dot(B))    ## Matrix Multiplication


[[2 0]
 [0 4]] 


 [[5 4]
 [3 4]]


In [11]:
#np.arange(12).reshape(4,3)
np.random.random(12).reshape(4,3)

array([[0.85374136, 0.13403774, 0.98709326],
       [0.08175941, 0.30542141, 0.86909431],
       [0.37364276, 0.39561665, 0.84698197],
       [0.60926562, 0.84312484, 0.87220521]])

In [31]:
#other built in funtions
zz=int(16)
print(zz)
print(np.sqrt(zz))
#print(np.exp(zz))
print(np.sin(30))
print(np.sin(np.deg2rad(30)))

16
4.0
-0.9880316240928618
0.49999999999999994


In [33]:
var_b = np.random.randint(1,20, size=(3,3))
print(var_b)

[[18 11 19]
 [ 4 14 19]
 [ 2 16  9]]


In [50]:
print("Sum of Columns",var_b.sum(axis=0)) ## the sum of values of columns
print("Sum of Rows",var_b.sum(axis=1)) ## the sum of values of columns
print("Max value",var_b.max())
print("Total sum",var_b.sum())
print("Minimum value",var_b.min())
print("Mean value",var_b.mean())
print("Standard deviation",var_b.std())

Sum of Columns [17 41 54]
Sum of Rows [27 37 48]
Max value 19
Total sum 112
Minimum value 2
Mean value 12.444444444444445
Standard deviation 6.020540970730696


In [54]:
#converting a multi dimensional array to a single dimensional array
print("var_b=\n",var_b)
var_c = var_b.ravel()
print("var_c = ",var_c)

var_b=
 [[ 2  9 16]
 [ 4 14 19]
 [11 18 19]]
var_c =  [ 2  9 16  4 14 19 11 18 19]


In [63]:
var_d = np.resize(var_c,(5,2))
print(var_d)
#note : here var_c had only 9 elements. when we reshared it to 5x2 it required 10 elements, 
# in this case it reuse or loop through the elements of the source

[[ 2  9]
 [16  4]
 [14 19]
 [11 18]
 [19  2]]


In [65]:
#one more example
var_e = np.resize(var_c,(4,3))
print(var_e)
#it is seen that the first row is repeated again

[[ 2  9 16]
 [ 4 14 19]
 [11 18 19]
 [ 2  9 16]]


Stacking array together
vstack -> vertical stack
hstack -> horizontal stack


In [67]:
stk_a =np.arange(1,5).reshape(2,2)
stk_b= np.arange(4,8).reshape(2,2)

print("stk_a=\n",stk_a,"\nstk_b=\n",stk_b)

stk_a=
 [[1 2]
 [3 4]] 
stk_b=
 [[4 5]
 [6 7]]


In [69]:
stk_vs=np.vstack((stk_a,stk_b))
print(stk_vs)
print("\n")
stk_hs=np.hstack((stk_a,stk_b))
print(stk_hs)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


[[1 2 4 5]
 [3 4 6 7]]


In [80]:
#Shallow copy and deep copy
shallow_a = np.arange(1,15)
print("shallow_a",shallow_a)
shallow_b = shallow_a
print("shallow_b", shallow_b)

print("updating value of 5th element of shallow_b to 99\n")
shallow_b[4]=99

print("shallow_b", shallow_b, "\nThe change was expected\n") 

print("shallow_a",shallow_a,"\nThe change was un-expected\n")

print("inshort a=b kind of assignment is similar to an alias and technically they are the same.")
print("this kind of copy is called shallow copy")

shallow_a [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
shallow_b [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
updating value of 5th element of shallow_b to 99

shallow_b [ 1  2  3  4 99  6  7  8  9 10 11 12 13 14] 
The change was expected

shallow_a [ 1  2  3  4 99  6  7  8  9 10 11 12 13 14] 
The change was un-expected

inshort a=b kind of assignment is similar to an alias and technically they are the same.
this kind of copy is called shallow copy


In [83]:
#Deep Copy
deep_a = np.arange(1,15)
print("deep_a",deep_a,"\n")
deep_b = deep_a.copy()
print("deep_b",deep_b,"\n")

print("updating value of 5th element of deep_b to 99\n")
deep_b[4]=99

print("deep_b", deep_b, "\nThe change was expected\n") 

print("deep_a",deep_a,"\n no change, as expected\n")

deep_a [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

deep_b [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

updating value of 5th element of deep_b to 99

deep_b [ 1  2  3  4 99  6  7  8  9 10 11 12 13 14] 
The change was expected

deep_a [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
 no change, as expected



#### Why Numpy over python list?

##### 1) The numpy list is smaller in size thus faster!

In [86]:
import sys
import time

In [124]:
#Python list
pyt_lst =list(range(1,151))  ### creating a list with elemetns from 1 to 150
print("\npython list size :",sys.getsizeof(pyt_lst))


python list size : 1456


In [125]:
#Numpy list
npy_lst =np.arange(1,151,1) ### creating a list with elemetns from 1 to 150
print("\nnumpy list size:",sys.getsizeof(npy_lst))


numpy list size: 696


In [100]:
type(Si_n)

numpy.ndarray

##### 2) Simpler calculations 

In [127]:
height = [1.72,1.65,1.66,1.78,1.9]
weight = [75,54,62,74,80]

In [137]:
# BMI = height in Weight/(height^2(in meters))
#
#weight/height**2  ==> this code will fail
#
for i in range (0,len(height),1) :
    print(weight[i]/height[i]**2)

25.351541373715524
19.834710743801654
22.49963710262738
23.355636914530994
22.1606648199446


In [133]:
npy_height = np.array(height)
npy_weight = np.array(weight)

print(npy_weight/(npy_height**2))

[25.35154137 19.83471074 22.4996371  23.35563691 22.16066482]


##### Here you could skip all those looping statemetns just by using numpy lists

##### Some Points to remember

In [140]:
pyt_lst2 = [1,"a",3.14,True]
npy_lst2 = np.array([1,"a",3.14,True])

In [141]:
print("pyt_lst2 = ",pyt_lst2,"\n")
print("npy_lst2 = ",npy_lst2)

pyt_lst2 =  [1, 'a', 3.14, True] 

npy_lst2 =  ['1' 'a' '3.14' 'True']


Here python list mainitains the input data type as it is, but <br> 
numpy converts all into a common data type, here all as string