# Python Packages Numpy and Pandas

In [1]:
#Importing packages with alias
import pandas as pd
import numpy as np

### Numpy

In [2]:
#creating a series of numbers lets say 1 to 15

a =np.arange(15) ## 0 to n-1, here (15-1)
b =np.arange(5,15) ## starting from 5 to 14
c =np.arange(0,15,2) ## staring form 1 to 14, with an interval of 2

print(" a=",a,"\n","b=",b,"\n","c=",c)

 a= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
 b= [ 5  6  7  8  9 10 11 12 13 14] 
 c= [ 0  2  4  6  8 10 12 14]


In [3]:
# 'a' is 1x15 in dimension, to convert it to 3x5
print ("reshape function \n",a.reshape(3,5),"\n") ## the change is temporary
print("checking after reshape function \n",a,"\n")
a.resize(3,5)  ## the change is permenant
print("check for a after resize \n",a)

reshape function 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

checking after reshape function 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

check for a after resize 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
#Creating a multi diamentional array
np.random.randint(1,25,size=(5,4))

array([[ 1,  3, 19, 22],
       [21, 23, 15,  3],
       [13, 12,  5, 13],
       [19, 24,  8, 22],
       [22, 17,  2,  8]])

##### There are a lot of functions, all of which cannot be explanined. if done so this will become the help file. <br>  So pls be familiar with the commands and the remaining things like syntax and useage could be obtained form inbuilt help/google

Help about a pirticular function can be obtained as follows. <br>
To see list of functions avaiable on numpy. <br>
just type "numpy." or "np."(if using alias)  and press tab

In [5]:
# Syntax
# np.info(np.function_name)
np.info(np.random.randint)

randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

Parameters
----------
low : int
    Lowest (signed) integer to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result. All dtypes are determined by their
    name, i.e., 'int64', 'int'

In [6]:
print(a,"\n")
print("the shape of array a:",a.shape)
print("the dimension of array a:",a.ndim)
print("the total no of elements in array a:",a.size)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

the shape of array a: (3, 5)
the dimension of array a: 2
the total no of elements in array a: 15


In [7]:
#array creation
aa =np.array([1,2,3,4,5])  ## Regular array
ab=np.array([[1, 2], [3, 4]]) ## Multi dimesnional array
ac=np.array([[1,2],[5,6]],dtype = complex) ## complex

print ("Regular Array\n",aa, "\nMulti Dimensional Array\n",ab,"\nComplex Array\n",ac)

Regular Array
 [1 2 3 4 5] 
Multi Dimensional Array
 [[1 2]
 [3 4]] 
Complex Array
 [[1.+0.j 2.+0.j]
 [5.+0.j 6.+0.j]]


In [8]:
## Few more numpy operations

print(np.zeros((2,2)))
print("\n")
print(np.ones((2,2),dtype = int))

[[0. 0.]
 [0. 0.]]


[[1 1]
 [1 1]]


In [9]:
#operations in numpy lists

A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print("A= \n",A,"\nB=\n",B)

A= 
 [[1 1]
 [0 1]] 
B=
 [[2 0]
 [3 4]]


In [10]:
print(A*B,"\n")         ## Element wise multiplication
print("\n",A.dot(B))    ## Matrix Multiplication


[[2 0]
 [0 4]] 


 [[5 4]
 [3 4]]


In [11]:
#np.arange(12).reshape(4,3)
np.random.random(12).reshape(4,3)

array([[0.85374136, 0.13403774, 0.98709326],
       [0.08175941, 0.30542141, 0.86909431],
       [0.37364276, 0.39561665, 0.84698197],
       [0.60926562, 0.84312484, 0.87220521]])

In [31]:
#other built in funtions
zz=int(16)
print(zz)
print(np.sqrt(zz))
#print(np.exp(zz))
print(np.sin(30))
print(np.sin(np.deg2rad(30)))

16
4.0
-0.9880316240928618
0.49999999999999994


In [33]:
var_b = np.random.randint(1,20, size=(3,3))
print(var_b)

[[18 11 19]
 [ 4 14 19]
 [ 2 16  9]]


In [50]:
print("Sum of Columns",var_b.sum(axis=0)) ## the sum of values of columns
print("Sum of Rows",var_b.sum(axis=1)) ## the sum of values of columns
print("Max value",var_b.max())
print("Total sum",var_b.sum())
print("Minimum value",var_b.min())
print("Mean value",var_b.mean())
print("Standard deviation",var_b.std())

Sum of Columns [17 41 54]
Sum of Rows [27 37 48]
Max value 19
Total sum 112
Minimum value 2
Mean value 12.444444444444445
Standard deviation 6.020540970730696
